apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: Hello-India-deployment 
spec: 
  selector: 
    matchLabels: 
      app: Hello-India 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: Hello-India 
    spec: 
      containers: 
      - name: Hello-India 
        image: Javedk/Hello-India::#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: Hello-India-service 
spec: 
  selector: 
    app: Hello-India 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
